services:
  postgres:
    image: ankane/pgvector:latest
    container_name: pitayacore-pgvector
    restart: always
    environment:
      POSTGRES_USER: acuacore_user
      POSTGRES_PASSWORD: acuacore_pass
      POSTGRES_DB: pitayacore_vector
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pitaya_net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: pitayacore-api
    restart: always
    env_file:
      - ./api/.env.pitayacore
    ports:
      - "3015:3015"
    networks:
      - pitaya_net
    volumes:
      - ./api/public/uploads:/app/public/uploads
    depends_on:
      - postgres

networks:
  pitaya_net:
    external: true

volumes:
  postgres_data:
