services:
  mysql:
    image: mysql:8
    container_name: pitaya-mysql-prod
    restart: always
    env_file:
      - ./api/.env.prod
    ports:
      - "3306:3306"
    volumes:
      - pitaya_mysql_data:/var/lib/mysql
    networks:
      - pitayacode_net

  postgres:
    image: ankane/pgvector:latest
    container_name: pitaya-postgres-prod
    restart: always
    env_file:
      - ./api/.env.prod
    ports:
      - "5432:5432"
    volumes:
      - pitaya_postgres_data:/var/lib/postgresql/data
    networks:
      - pitayacode_net

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: pitayacore-api
    restart: always
    env_file:
      - ./api/.env.prod
    ports:
      - "3015:3015"
    networks:
      - pitayacode_net
    volumes:
      - pitaya_storage:/app/.storage
      - ./api/public/uploads:/app/public/uploads
    depends_on:
      - mysql
      - postgres

networks:
  pitayacode_net:
    external: true

volumes:
  pitaya_mysql_data:
  pitaya_postgres_data:
  pitaya_storage:
